dataset: CIFAR100
first_split_size: 10
other_split_size: 10
schedule:
- 50
schedule_type: cosine_torch
batch_size: 256
optimizer: AdamW
lr: 1e-3
momentum: 0.9
weight_decay: 0
model_type: zoo
model_name: vit_free_imnet
max_task: -1
dataroot: data
workers: 2
validation: False
train_aug: True
rand_split: True